# Generated by Django 5.2 on 2025-05-03 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/project_items/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('project_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.projectitem')),
            ],
        ),
    ]
