# Generated by Django 5.2 on 2025-05-03 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_projectitemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectitemimage',
            name='project_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='store.projectitem'),
        ),
    ]
