# Generated by Django 5.2 on 2025-05-03 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_projectitemimage_project_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/furniture_items/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('furniture_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='furniture_images', to='store.furniture')),
            ],
        ),
    ]
